logging:
  level:
    com:
      eureka:
        serviceconsumer: debug

server:
  port: 6060

spring:
  application:
    name: service-consumer

# 配置eureka 服务提供者
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7070/eureka,http://${eureka.instance.hostname}:7071/eureka

service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 配置Hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms

circuitBreaker:
  requestVolumeThreshold: 5
  sleepWindowInMilliseconds: 10000
  errorThresholdPercentage: 50

# 开启feign熔断功能
feign:
  hystrix:
    enabled: true

  # 开启请求/响应压缩
  compression:
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
    response:
      enabled: true # 开启响应压缩